// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.AdminMessage in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Admin message for device configuration
 * Field numbers must match official Meshtastic protobufs
 */
public class AdminMessage(
  /**
   * Get channel by index (request)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    jsonName = "getChannelRequest",
    oneofName = "payload_variant",
    schemaIndex = 0,
  )
  public val get_channel_request: Int? = null,
  /**
   * Get channel response
   */
  @field:WireField(
    tag = 2,
    adapter = "com.bitchat.lora.meshtastic.proto.Channel#ADAPTER",
    jsonName = "getChannelResponse",
    oneofName = "payload_variant",
    schemaIndex = 1,
  )
  public val get_channel_response: Channel? = null,
  /**
   * Get config request (ConfigType enum value)
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    jsonName = "getConfigRequest",
    oneofName = "payload_variant",
    schemaIndex = 2,
  )
  public val get_config_request: Int? = null,
  /**
   * Get config response
   */
  @field:WireField(
    tag = 6,
    adapter = "com.bitchat.lora.meshtastic.proto.Config#ADAPTER",
    jsonName = "getConfigResponse",
    oneofName = "payload_variant",
    schemaIndex = 3,
  )
  public val get_config_response: Config? = null,
  /**
   * Set channel configuration
   */
  @field:WireField(
    tag = 33,
    adapter = "com.bitchat.lora.meshtastic.proto.Channel#ADAPTER",
    jsonName = "setChannel",
    oneofName = "payload_variant",
    schemaIndex = 4,
  )
  public val set_channel: Channel? = null,
  /**
   * Set config
   */
  @field:WireField(
    tag = 34,
    adapter = "com.bitchat.lora.meshtastic.proto.Config#ADAPTER",
    jsonName = "setConfig",
    oneofName = "payload_variant",
    schemaIndex = 5,
  )
  public val set_config: Config? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<AdminMessage, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(get_channel_request, get_channel_response, get_config_request, get_config_response, set_channel, set_config) <= 1) {
      "At most one of get_channel_request, get_channel_response, get_config_request, get_config_response, set_channel, set_config may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is AdminMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (get_channel_request != other.get_channel_request) return false
    if (get_channel_response != other.get_channel_response) return false
    if (get_config_request != other.get_config_request) return false
    if (get_config_response != other.get_config_response) return false
    if (set_channel != other.set_channel) return false
    if (set_config != other.set_config) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (get_channel_request?.hashCode() ?: 0)
      result = result * 37 + (get_channel_response?.hashCode() ?: 0)
      result = result * 37 + (get_config_request?.hashCode() ?: 0)
      result = result * 37 + (get_config_response?.hashCode() ?: 0)
      result = result * 37 + (set_channel?.hashCode() ?: 0)
      result = result * 37 + (set_config?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (get_channel_request != null) result += """get_channel_request=$get_channel_request"""
    if (get_channel_response != null) result += """get_channel_response=$get_channel_response"""
    if (get_config_request != null) result += """get_config_request=$get_config_request"""
    if (get_config_response != null) result += """get_config_response=$get_config_response"""
    if (set_channel != null) result += """set_channel=$set_channel"""
    if (set_config != null) result += """set_config=$set_config"""
    return result.joinToString(prefix = "AdminMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    get_channel_request: Int? = this.get_channel_request,
    get_channel_response: Channel? = this.get_channel_response,
    get_config_request: Int? = this.get_config_request,
    get_config_response: Config? = this.get_config_response,
    set_channel: Channel? = this.set_channel,
    set_config: Config? = this.set_config,
    unknownFields: ByteString = this.unknownFields,
  ): AdminMessage = AdminMessage(get_channel_request, get_channel_response, get_config_request, get_config_response, set_channel, set_config, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<AdminMessage> = object : ProtoAdapter<AdminMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      AdminMessage::class, 
      "type.googleapis.com/meshtastic.AdminMessage", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: AdminMessage): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.get_channel_request)
        size += Channel.ADAPTER.encodedSizeWithTag(2, value.get_channel_response)
        size += ProtoAdapter.UINT32.encodedSizeWithTag(5, value.get_config_request)
        size += Config.ADAPTER.encodedSizeWithTag(6, value.get_config_response)
        size += Channel.ADAPTER.encodedSizeWithTag(33, value.set_channel)
        size += Config.ADAPTER.encodedSizeWithTag(34, value.set_config)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: AdminMessage) {
        ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.get_channel_request)
        Channel.ADAPTER.encodeWithTag(writer, 2, value.get_channel_response)
        ProtoAdapter.UINT32.encodeWithTag(writer, 5, value.get_config_request)
        Config.ADAPTER.encodeWithTag(writer, 6, value.get_config_response)
        Channel.ADAPTER.encodeWithTag(writer, 33, value.set_channel)
        Config.ADAPTER.encodeWithTag(writer, 34, value.set_config)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: AdminMessage) {
        writer.writeBytes(value.unknownFields)
        Config.ADAPTER.encodeWithTag(writer, 34, value.set_config)
        Channel.ADAPTER.encodeWithTag(writer, 33, value.set_channel)
        Config.ADAPTER.encodeWithTag(writer, 6, value.get_config_response)
        ProtoAdapter.UINT32.encodeWithTag(writer, 5, value.get_config_request)
        Channel.ADAPTER.encodeWithTag(writer, 2, value.get_channel_response)
        ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.get_channel_request)
      }

      override fun decode(reader: ProtoReader): AdminMessage {
        var get_channel_request: Int? = null
        var get_channel_response: Channel? = null
        var get_config_request: Int? = null
        var get_config_response: Config? = null
        var set_channel: Channel? = null
        var set_config: Config? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> get_channel_request = ProtoAdapter.UINT32.decode(reader)
            2 -> get_channel_response = Channel.ADAPTER.decode(reader)
            5 -> get_config_request = ProtoAdapter.UINT32.decode(reader)
            6 -> get_config_response = Config.ADAPTER.decode(reader)
            33 -> set_channel = Channel.ADAPTER.decode(reader)
            34 -> set_config = Config.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return AdminMessage(
          get_channel_request = get_channel_request,
          get_channel_response = get_channel_response,
          get_config_request = get_config_request,
          get_config_response = get_config_response,
          set_channel = set_channel,
          set_config = set_config,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: AdminMessage): AdminMessage = value.copy(
        get_channel_response = value.get_channel_response?.let(Channel.ADAPTER::redact),
        get_config_response = value.get_config_response?.let(Config.ADAPTER::redact),
        set_channel = value.set_channel?.let(Channel.ADAPTER::redact),
        set_config = value.set_config?.let(Config.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
