// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.Channel in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * A channel configuration
 */
public class Channel(
  /**
   * Channel index (0 = PRIMARY, 1-7 = SECONDARY)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val index: Int = 0,
  /**
   * Channel settings
   */
  @field:WireField(
    tag = 2,
    adapter = "com.bitchat.lora.meshtastic.proto.ChannelSettings#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val settings: ChannelSettings? = null,
  /**
   * Channel role
   */
  @field:WireField(
    tag = 3,
    adapter = "com.bitchat.lora.meshtastic.proto.Channel_Role#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val role: Channel_Role = Channel_Role.DISABLED,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Channel, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Channel) return false
    if (unknownFields != other.unknownFields) return false
    if (index != other.index) return false
    if (settings != other.settings) return false
    if (role != other.role) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + index.hashCode()
      result = result * 37 + (settings?.hashCode() ?: 0)
      result = result * 37 + role.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """index=$index"""
    if (settings != null) result += """settings=$settings"""
    result += """role=$role"""
    return result.joinToString(prefix = "Channel{", separator = ", ", postfix = "}")
  }

  public fun copy(
    index: Int = this.index,
    settings: ChannelSettings? = this.settings,
    role: Channel_Role = this.role,
    unknownFields: ByteString = this.unknownFields,
  ): Channel = Channel(index, settings, role, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Channel> = object : ProtoAdapter<Channel>(
      FieldEncoding.LENGTH_DELIMITED, 
      Channel::class, 
      "type.googleapis.com/meshtastic.Channel", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: Channel): Int {
        var size = value.unknownFields.size
        if (value.index != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.index)
        }
        if (value.settings != null) {
          size += ChannelSettings.ADAPTER.encodedSizeWithTag(2, value.settings)
        }
        if (value.role != com.bitchat.lora.meshtastic.proto.Channel_Role.DISABLED) {
          size += Channel_Role.ADAPTER.encodedSizeWithTag(3, value.role)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Channel) {
        if (value.index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.index)
        }
        if (value.settings != null) {
          ChannelSettings.ADAPTER.encodeWithTag(writer, 2, value.settings)
        }
        if (value.role != com.bitchat.lora.meshtastic.proto.Channel_Role.DISABLED) {
          Channel_Role.ADAPTER.encodeWithTag(writer, 3, value.role)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Channel) {
        writer.writeBytes(value.unknownFields)
        if (value.role != com.bitchat.lora.meshtastic.proto.Channel_Role.DISABLED) {
          Channel_Role.ADAPTER.encodeWithTag(writer, 3, value.role)
        }
        if (value.settings != null) {
          ChannelSettings.ADAPTER.encodeWithTag(writer, 2, value.settings)
        }
        if (value.index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.index)
        }
      }

      override fun decode(reader: ProtoReader): Channel {
        var index: Int = 0
        var settings: ChannelSettings? = null
        var role: Channel_Role = Channel_Role.DISABLED
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> index = ProtoAdapter.INT32.decode(reader)
            2 -> settings = ChannelSettings.ADAPTER.decode(reader)
            3 -> try {
              role = Channel_Role.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            else -> reader.readUnknownField(tag)
          }
        }
        return Channel(
          index = index,
          settings = settings,
          role = role,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Channel): Channel = value.copy(
        settings = value.settings?.let(ChannelSettings.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
