// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.Channel_Role in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Channel role
 */
public enum class Channel_Role(
  override val `value`: Int,
) : WireEnum {
  DISABLED(0),
  PRIMARY(1),
  SECONDARY(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Channel_Role> = object : EnumAdapter<Channel_Role>(
      Channel_Role::class, 
      PROTO_3, 
      Channel_Role.DISABLED
    ) {
      override fun fromValue(`value`: Int): Channel_Role? = Channel_Role.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): Channel_Role? = when (`value`) {
      0 -> DISABLED
      1 -> PRIMARY
      2 -> SECONDARY
      else -> null
    }
  }
}
