// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.ChannelSettings in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Channel settings (encryption, naming)
 */
public class ChannelSettings(
  /**
   * Deprecated channel number (use Channel.index instead)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "channelNum",
    schemaIndex = 0,
  )
  public val channel_num: Int = 0,
  /**
   * Pre-shared key: 0 bytes (none), 16 bytes (AES128), or 32 bytes (AES256)
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val psk: ByteString = ByteString.EMPTY,
  /**
   * Channel name (for display)
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val name: String = "",
  /**
   * Fixed 8-byte ID (derived from name+psk if not set)
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val id: Int = 0,
  /**
   * Uplink enabled (for MQTT gateway)
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "uplinkEnabled",
    schemaIndex = 4,
  )
  public val uplink_enabled: Boolean = false,
  /**
   * Downlink enabled (for MQTT gateway)
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "downlinkEnabled",
    schemaIndex = 5,
  )
  public val downlink_enabled: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ChannelSettings, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChannelSettings) return false
    if (unknownFields != other.unknownFields) return false
    if (channel_num != other.channel_num) return false
    if (psk != other.psk) return false
    if (name != other.name) return false
    if (id != other.id) return false
    if (uplink_enabled != other.uplink_enabled) return false
    if (downlink_enabled != other.downlink_enabled) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + channel_num.hashCode()
      result = result * 37 + psk.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + uplink_enabled.hashCode()
      result = result * 37 + downlink_enabled.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """channel_num=$channel_num"""
    result += """psk=$psk"""
    result += """name=${sanitize(name)}"""
    result += """id=$id"""
    result += """uplink_enabled=$uplink_enabled"""
    result += """downlink_enabled=$downlink_enabled"""
    return result.joinToString(prefix = "ChannelSettings{", separator = ", ", postfix = "}")
  }

  public fun copy(
    channel_num: Int = this.channel_num,
    psk: ByteString = this.psk,
    name: String = this.name,
    id: Int = this.id,
    uplink_enabled: Boolean = this.uplink_enabled,
    downlink_enabled: Boolean = this.downlink_enabled,
    unknownFields: ByteString = this.unknownFields,
  ): ChannelSettings = ChannelSettings(channel_num, psk, name, id, uplink_enabled, downlink_enabled, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChannelSettings> = object : ProtoAdapter<ChannelSettings>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChannelSettings::class, 
      "type.googleapis.com/meshtastic.ChannelSettings", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: ChannelSettings): Int {
        var size = value.unknownFields.size
        if (value.channel_num != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.channel_num)
        }
        if (value.psk != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(2, value.psk)
        }
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.name)
        }
        if (value.id != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(4, value.id)
        }
        if (value.uplink_enabled != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(5, value.uplink_enabled)
        }
        if (value.downlink_enabled != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(6, value.downlink_enabled)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChannelSettings) {
        if (value.channel_num != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.channel_num)
        }
        if (value.psk != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.psk)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.name)
        }
        if (value.id != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 4, value.id)
        }
        if (value.uplink_enabled != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.uplink_enabled)
        }
        if (value.downlink_enabled != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.downlink_enabled)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChannelSettings) {
        writer.writeBytes(value.unknownFields)
        if (value.downlink_enabled != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.downlink_enabled)
        }
        if (value.uplink_enabled != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.uplink_enabled)
        }
        if (value.id != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 4, value.id)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.name)
        }
        if (value.psk != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.psk)
        }
        if (value.channel_num != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.channel_num)
        }
      }

      override fun decode(reader: ProtoReader): ChannelSettings {
        var channel_num: Int = 0
        var psk: ByteString = ByteString.EMPTY
        var name: String = ""
        var id: Int = 0
        var uplink_enabled: Boolean = false
        var downlink_enabled: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> channel_num = ProtoAdapter.UINT32.decode(reader)
            2 -> psk = ProtoAdapter.BYTES.decode(reader)
            3 -> name = ProtoAdapter.STRING.decode(reader)
            4 -> id = ProtoAdapter.FIXED32.decode(reader)
            5 -> uplink_enabled = ProtoAdapter.BOOL.decode(reader)
            6 -> downlink_enabled = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ChannelSettings(
          channel_num = channel_num,
          psk = psk,
          name = name,
          id = id,
          uplink_enabled = uplink_enabled,
          downlink_enabled = downlink_enabled,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChannelSettings): ChannelSettings = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
