// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.Config in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Device configuration container
 */
public class Config(
  /**
   * LoRa radio configuration
   */
  @field:WireField(
    tag = 3,
    adapter = "com.bitchat.lora.meshtastic.proto.LoRaConfig#ADAPTER",
    oneofName = "payload_variant",
    schemaIndex = 0,
  )
  public val lora: LoRaConfig? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Config, Nothing>(ADAPTER, unknownFields) {
  init {
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Config) return false
    if (unknownFields != other.unknownFields) return false
    if (lora != other.lora) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (lora?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (lora != null) result += """lora=$lora"""
    return result.joinToString(prefix = "Config{", separator = ", ", postfix = "}")
  }

  public fun copy(lora: LoRaConfig? = this.lora, unknownFields: ByteString = this.unknownFields): Config = Config(lora, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Config> = object : ProtoAdapter<Config>(
      FieldEncoding.LENGTH_DELIMITED, 
      Config::class, 
      "type.googleapis.com/meshtastic.Config", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: Config): Int {
        var size = value.unknownFields.size
        size += LoRaConfig.ADAPTER.encodedSizeWithTag(3, value.lora)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Config) {
        LoRaConfig.ADAPTER.encodeWithTag(writer, 3, value.lora)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Config) {
        writer.writeBytes(value.unknownFields)
        LoRaConfig.ADAPTER.encodeWithTag(writer, 3, value.lora)
      }

      override fun decode(reader: ProtoReader): Config {
        var lora: LoRaConfig? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            3 -> lora = LoRaConfig.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Config(
          lora = lora,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Config): Config = value.copy(
        lora = value.lora?.let(LoRaConfig.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
