// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.Data in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Application-layer data
 */
public class Data(
  /**
   * Port number this is addressed to
   */
  @field:WireField(
    tag = 1,
    adapter = "com.bitchat.lora.meshtastic.proto.PortNum#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val portnum: PortNum = PortNum.UNKNOWN_APP,
  /**
   * Payload bytes
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val payload: ByteString = ByteString.EMPTY,
  /**
   * Want response?
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "wantResponse",
    schemaIndex = 2,
  )
  public val want_response: Boolean = false,
  /**
   * Destination node number for response
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val dest: Int = 0,
  /**
   * Source node number
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val source: Int = 0,
  /**
   * Request ID if this is a response
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "requestId",
    schemaIndex = 5,
  )
  public val request_id: Int = 0,
  /**
   * Reply ID
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "replyId",
    schemaIndex = 6,
  )
  public val reply_id: Int = 0,
  /**
   * Emoji response
   */
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val emoji: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Data, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Data) return false
    if (unknownFields != other.unknownFields) return false
    if (portnum != other.portnum) return false
    if (payload != other.payload) return false
    if (want_response != other.want_response) return false
    if (dest != other.dest) return false
    if (source != other.source) return false
    if (request_id != other.request_id) return false
    if (reply_id != other.reply_id) return false
    if (emoji != other.emoji) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + portnum.hashCode()
      result = result * 37 + payload.hashCode()
      result = result * 37 + want_response.hashCode()
      result = result * 37 + dest.hashCode()
      result = result * 37 + source.hashCode()
      result = result * 37 + request_id.hashCode()
      result = result * 37 + reply_id.hashCode()
      result = result * 37 + emoji.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """portnum=$portnum"""
    result += """payload=$payload"""
    result += """want_response=$want_response"""
    result += """dest=$dest"""
    result += """source=$source"""
    result += """request_id=$request_id"""
    result += """reply_id=$reply_id"""
    result += """emoji=$emoji"""
    return result.joinToString(prefix = "Data{", separator = ", ", postfix = "}")
  }

  public fun copy(
    portnum: PortNum = this.portnum,
    payload: ByteString = this.payload,
    want_response: Boolean = this.want_response,
    dest: Int = this.dest,
    source: Int = this.source,
    request_id: Int = this.request_id,
    reply_id: Int = this.reply_id,
    emoji: Int = this.emoji,
    unknownFields: ByteString = this.unknownFields,
  ): Data = Data(portnum, payload, want_response, dest, source, request_id, reply_id, emoji, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Data> = object : ProtoAdapter<Data>(
      FieldEncoding.LENGTH_DELIMITED, 
      Data::class, 
      "type.googleapis.com/meshtastic.Data", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: Data): Int {
        var size = value.unknownFields.size
        if (value.portnum != com.bitchat.lora.meshtastic.proto.PortNum.UNKNOWN_APP) {
          size += PortNum.ADAPTER.encodedSizeWithTag(1, value.portnum)
        }
        if (value.payload != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(2, value.payload)
        }
        if (value.want_response != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.want_response)
        }
        if (value.dest != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(4, value.dest)
        }
        if (value.source != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(5, value.source)
        }
        if (value.request_id != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(6, value.request_id)
        }
        if (value.reply_id != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(7, value.reply_id)
        }
        if (value.emoji != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(8, value.emoji)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Data) {
        if (value.portnum != com.bitchat.lora.meshtastic.proto.PortNum.UNKNOWN_APP) {
          PortNum.ADAPTER.encodeWithTag(writer, 1, value.portnum)
        }
        if (value.payload != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.payload)
        }
        if (value.want_response != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.want_response)
        }
        if (value.dest != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 4, value.dest)
        }
        if (value.source != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 5, value.source)
        }
        if (value.request_id != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 6, value.request_id)
        }
        if (value.reply_id != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 7, value.reply_id)
        }
        if (value.emoji != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 8, value.emoji)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Data) {
        writer.writeBytes(value.unknownFields)
        if (value.emoji != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 8, value.emoji)
        }
        if (value.reply_id != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 7, value.reply_id)
        }
        if (value.request_id != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 6, value.request_id)
        }
        if (value.source != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 5, value.source)
        }
        if (value.dest != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 4, value.dest)
        }
        if (value.want_response != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.want_response)
        }
        if (value.payload != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.payload)
        }
        if (value.portnum != com.bitchat.lora.meshtastic.proto.PortNum.UNKNOWN_APP) {
          PortNum.ADAPTER.encodeWithTag(writer, 1, value.portnum)
        }
      }

      override fun decode(reader: ProtoReader): Data {
        var portnum: PortNum = PortNum.UNKNOWN_APP
        var payload: ByteString = ByteString.EMPTY
        var want_response: Boolean = false
        var dest: Int = 0
        var source: Int = 0
        var request_id: Int = 0
        var reply_id: Int = 0
        var emoji: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              portnum = PortNum.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> payload = ProtoAdapter.BYTES.decode(reader)
            3 -> want_response = ProtoAdapter.BOOL.decode(reader)
            4 -> dest = ProtoAdapter.FIXED32.decode(reader)
            5 -> source = ProtoAdapter.FIXED32.decode(reader)
            6 -> request_id = ProtoAdapter.FIXED32.decode(reader)
            7 -> reply_id = ProtoAdapter.FIXED32.decode(reader)
            8 -> emoji = ProtoAdapter.FIXED32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Data(
          portnum = portnum,
          payload = payload,
          want_response = want_response,
          dest = dest,
          source = source,
          request_id = request_id,
          reply_id = reply_id,
          emoji = emoji,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Data): Data = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
