// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.DeviceMetrics in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Device metrics
 */
public class DeviceMetrics(
  /**
   * Battery level (0-100)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "batteryLevel",
    schemaIndex = 0,
  )
  public val battery_level: Int = 0,
  /**
   * Voltage
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val voltage: Float = 0f,
  /**
   * Channel utilization percent
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "channelUtilization",
    schemaIndex = 2,
  )
  public val channel_utilization: Float = 0f,
  /**
   * Airtime utilization percent
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "airUtilTx",
    schemaIndex = 3,
  )
  public val air_util_tx: Float = 0f,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<DeviceMetrics, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is DeviceMetrics) return false
    if (unknownFields != other.unknownFields) return false
    if (battery_level != other.battery_level) return false
    if (voltage != other.voltage) return false
    if (channel_utilization != other.channel_utilization) return false
    if (air_util_tx != other.air_util_tx) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + battery_level.hashCode()
      result = result * 37 + voltage.hashCode()
      result = result * 37 + channel_utilization.hashCode()
      result = result * 37 + air_util_tx.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """battery_level=$battery_level"""
    result += """voltage=$voltage"""
    result += """channel_utilization=$channel_utilization"""
    result += """air_util_tx=$air_util_tx"""
    return result.joinToString(prefix = "DeviceMetrics{", separator = ", ", postfix = "}")
  }

  public fun copy(
    battery_level: Int = this.battery_level,
    voltage: Float = this.voltage,
    channel_utilization: Float = this.channel_utilization,
    air_util_tx: Float = this.air_util_tx,
    unknownFields: ByteString = this.unknownFields,
  ): DeviceMetrics = DeviceMetrics(battery_level, voltage, channel_utilization, air_util_tx, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DeviceMetrics> = object : ProtoAdapter<DeviceMetrics>(
      FieldEncoding.LENGTH_DELIMITED, 
      DeviceMetrics::class, 
      "type.googleapis.com/meshtastic.DeviceMetrics", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: DeviceMetrics): Int {
        var size = value.unknownFields.size
        if (value.battery_level != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.battery_level)
        }
        if (!value.voltage.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(2, value.voltage)
        }
        if (!value.channel_utilization.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(3, value.channel_utilization)
        }
        if (!value.air_util_tx.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(4, value.air_util_tx)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: DeviceMetrics) {
        if (value.battery_level != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.battery_level)
        }
        if (!value.voltage.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.voltage)
        }
        if (!value.channel_utilization.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.channel_utilization)
        }
        if (!value.air_util_tx.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.air_util_tx)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: DeviceMetrics) {
        writer.writeBytes(value.unknownFields)
        if (!value.air_util_tx.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.air_util_tx)
        }
        if (!value.channel_utilization.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.channel_utilization)
        }
        if (!value.voltage.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.voltage)
        }
        if (value.battery_level != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.battery_level)
        }
      }

      override fun decode(reader: ProtoReader): DeviceMetrics {
        var battery_level: Int = 0
        var voltage: Float = 0f
        var channel_utilization: Float = 0f
        var air_util_tx: Float = 0f
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> battery_level = ProtoAdapter.UINT32.decode(reader)
            2 -> voltage = ProtoAdapter.FLOAT.decode(reader)
            3 -> channel_utilization = ProtoAdapter.FLOAT.decode(reader)
            4 -> air_util_tx = ProtoAdapter.FLOAT.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return DeviceMetrics(
          battery_level = battery_level,
          voltage = voltage,
          channel_utilization = channel_utilization,
          air_util_tx = air_util_tx,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: DeviceMetrics): DeviceMetrics = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
