// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.FromRadio in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Message from radio to app
 */
public class FromRadio(
  /**
   * Packet ID
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: Int = 0,
  /**
   * Received mesh packet
   */
  @field:WireField(
    tag = 2,
    adapter = "com.bitchat.lora.meshtastic.proto.MeshPacket#ADAPTER",
    oneofName = "payload_variant",
    schemaIndex = 1,
  )
  public val packet: MeshPacket? = null,
  /**
   * My node info
   */
  @field:WireField(
    tag = 3,
    adapter = "com.bitchat.lora.meshtastic.proto.MyNodeInfo#ADAPTER",
    jsonName = "myInfo",
    oneofName = "payload_variant",
    schemaIndex = 2,
  )
  public val my_info: MyNodeInfo? = null,
  /**
   * Node info update
   */
  @field:WireField(
    tag = 4,
    adapter = "com.bitchat.lora.meshtastic.proto.NodeInfo#ADAPTER",
    jsonName = "nodeInfo",
    oneofName = "payload_variant",
    schemaIndex = 3,
  )
  public val node_info: NodeInfo? = null,
  /**
   * Config (field 5 - we skip it but need placeholder)
   * Config config = 5;
   * Log message (field 6)
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "logRecord",
    oneofName = "payload_variant",
    schemaIndex = 4,
  )
  public val log_record: String? = null,
  /**
   * Config complete marker (field 7)
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    jsonName = "configCompleteId",
    oneofName = "payload_variant",
    schemaIndex = 5,
  )
  public val config_complete_id: Int? = null,
  /**
   * Rebooted indicator (field 8)
   */
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    oneofName = "payload_variant",
    schemaIndex = 6,
  )
  public val rebooted: Boolean? = null,
  /**
   * Channel (field 10)
   */
  @field:WireField(
    tag = 10,
    adapter = "com.bitchat.lora.meshtastic.proto.Channel#ADAPTER",
    oneofName = "payload_variant",
    schemaIndex = 7,
  )
  public val channel: Channel? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<FromRadio, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(packet, my_info, node_info, log_record, config_complete_id, rebooted, channel) <= 1) {
      "At most one of packet, my_info, node_info, log_record, config_complete_id, rebooted, channel may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FromRadio) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (packet != other.packet) return false
    if (my_info != other.my_info) return false
    if (node_info != other.node_info) return false
    if (log_record != other.log_record) return false
    if (config_complete_id != other.config_complete_id) return false
    if (rebooted != other.rebooted) return false
    if (channel != other.channel) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + (packet?.hashCode() ?: 0)
      result = result * 37 + (my_info?.hashCode() ?: 0)
      result = result * 37 + (node_info?.hashCode() ?: 0)
      result = result * 37 + (log_record?.hashCode() ?: 0)
      result = result * 37 + (config_complete_id?.hashCode() ?: 0)
      result = result * 37 + (rebooted?.hashCode() ?: 0)
      result = result * 37 + (channel?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=$id"""
    if (packet != null) result += """packet=$packet"""
    if (my_info != null) result += """my_info=$my_info"""
    if (node_info != null) result += """node_info=$node_info"""
    if (log_record != null) result += """log_record=${sanitize(log_record)}"""
    if (config_complete_id != null) result += """config_complete_id=$config_complete_id"""
    if (rebooted != null) result += """rebooted=$rebooted"""
    if (channel != null) result += """channel=$channel"""
    return result.joinToString(prefix = "FromRadio{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: Int = this.id,
    packet: MeshPacket? = this.packet,
    my_info: MyNodeInfo? = this.my_info,
    node_info: NodeInfo? = this.node_info,
    log_record: String? = this.log_record,
    config_complete_id: Int? = this.config_complete_id,
    rebooted: Boolean? = this.rebooted,
    channel: Channel? = this.channel,
    unknownFields: ByteString = this.unknownFields,
  ): FromRadio = FromRadio(id, packet, my_info, node_info, log_record, config_complete_id, rebooted, channel, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<FromRadio> = object : ProtoAdapter<FromRadio>(
      FieldEncoding.LENGTH_DELIMITED, 
      FromRadio::class, 
      "type.googleapis.com/meshtastic.FromRadio", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: FromRadio): Int {
        var size = value.unknownFields.size
        if (value.id != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.id)
        }
        size += MeshPacket.ADAPTER.encodedSizeWithTag(2, value.packet)
        size += MyNodeInfo.ADAPTER.encodedSizeWithTag(3, value.my_info)
        size += NodeInfo.ADAPTER.encodedSizeWithTag(4, value.node_info)
        size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.log_record)
        size += ProtoAdapter.UINT32.encodedSizeWithTag(7, value.config_complete_id)
        size += ProtoAdapter.BOOL.encodedSizeWithTag(8, value.rebooted)
        size += Channel.ADAPTER.encodedSizeWithTag(10, value.channel)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: FromRadio) {
        if (value.id != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.id)
        }
        MeshPacket.ADAPTER.encodeWithTag(writer, 2, value.packet)
        MyNodeInfo.ADAPTER.encodeWithTag(writer, 3, value.my_info)
        NodeInfo.ADAPTER.encodeWithTag(writer, 4, value.node_info)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.log_record)
        ProtoAdapter.UINT32.encodeWithTag(writer, 7, value.config_complete_id)
        ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.rebooted)
        Channel.ADAPTER.encodeWithTag(writer, 10, value.channel)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: FromRadio) {
        writer.writeBytes(value.unknownFields)
        Channel.ADAPTER.encodeWithTag(writer, 10, value.channel)
        ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.rebooted)
        ProtoAdapter.UINT32.encodeWithTag(writer, 7, value.config_complete_id)
        ProtoAdapter.STRING.encodeWithTag(writer, 6, value.log_record)
        NodeInfo.ADAPTER.encodeWithTag(writer, 4, value.node_info)
        MyNodeInfo.ADAPTER.encodeWithTag(writer, 3, value.my_info)
        MeshPacket.ADAPTER.encodeWithTag(writer, 2, value.packet)
        if (value.id != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): FromRadio {
        var id: Int = 0
        var packet: MeshPacket? = null
        var my_info: MyNodeInfo? = null
        var node_info: NodeInfo? = null
        var log_record: String? = null
        var config_complete_id: Int? = null
        var rebooted: Boolean? = null
        var channel: Channel? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.UINT32.decode(reader)
            2 -> packet = MeshPacket.ADAPTER.decode(reader)
            3 -> my_info = MyNodeInfo.ADAPTER.decode(reader)
            4 -> node_info = NodeInfo.ADAPTER.decode(reader)
            6 -> log_record = ProtoAdapter.STRING.decode(reader)
            7 -> config_complete_id = ProtoAdapter.UINT32.decode(reader)
            8 -> rebooted = ProtoAdapter.BOOL.decode(reader)
            10 -> channel = Channel.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return FromRadio(
          id = id,
          packet = packet,
          my_info = my_info,
          node_info = node_info,
          log_record = log_record,
          config_complete_id = config_complete_id,
          rebooted = rebooted,
          channel = channel,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: FromRadio): FromRadio = value.copy(
        packet = value.packet?.let(MeshPacket.ADAPTER::redact),
        my_info = value.my_info?.let(MyNodeInfo.ADAPTER::redact),
        node_info = value.node_info?.let(NodeInfo.ADAPTER::redact),
        channel = value.channel?.let(Channel.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
