// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.HardwareModel in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Hardware model types
 */
public enum class HardwareModel(
  override val `value`: Int,
) : WireEnum {
  UNSET(0),
  TLORA_V2(1),
  TLORA_V1(2),
  TLORA_V2_1_1P6(3),
  TBEAM(4),
  HELTEC_V2_0(5),
  TBEAM_V0P7(6),
  T_ECHO(7),
  TLORA_V1_1P3(8),
  RAK4631(9),
  HELTEC_V2_1(10),
  HELTEC_V1(11),
  LILYGO_TBEAM_S3_CORE(12),
  RAK11200(13),
  NANO_G1(14),
  TLORA_V2_1_1P8(15),
  STATION_G1(25),
  LORA_RELAY_V1(32),
  NRF52840DK(33),
  PPR(34),
  GENIEBLOCKS(35),
  NRF52_UNKNOWN(36),
  PORTDUINO(37),
  ANDROID_SIM(38),
  DIY_V1(39),
  NRF52840_PCA10059(40),
  DR_DEV(41),
  M5STACK(42),
  HELTEC_V3(43),
  HELTEC_WSL_V3(44),
  BETAFPV_2400_TX(45),
  BETAFPV_900_NANO_TX(46),
  RPI_PICO(47),
  HELTEC_WIRELESS_TRACKER(48),
  HELTEC_WIRELESS_PAPER(49),
  T_DECK(50),
  T_WATCH_S3(51),
  PICOMPUTER_S3(52),
  HELTEC_HT62(53),
  EBYTE_ESP32_S3(54),
  ESP32_S3_PICO(55),
  CHATTER_2(56),
  PRIVATE_HW(255),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<HardwareModel> = object : EnumAdapter<HardwareModel>(
      HardwareModel::class, 
      PROTO_3, 
      HardwareModel.UNSET
    ) {
      override fun fromValue(`value`: Int): HardwareModel? = HardwareModel.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): HardwareModel? = when (`value`) {
      0 -> UNSET
      1 -> TLORA_V2
      2 -> TLORA_V1
      3 -> TLORA_V2_1_1P6
      4 -> TBEAM
      5 -> HELTEC_V2_0
      6 -> TBEAM_V0P7
      7 -> T_ECHO
      8 -> TLORA_V1_1P3
      9 -> RAK4631
      10 -> HELTEC_V2_1
      11 -> HELTEC_V1
      12 -> LILYGO_TBEAM_S3_CORE
      13 -> RAK11200
      14 -> NANO_G1
      15 -> TLORA_V2_1_1P8
      25 -> STATION_G1
      32 -> LORA_RELAY_V1
      33 -> NRF52840DK
      34 -> PPR
      35 -> GENIEBLOCKS
      36 -> NRF52_UNKNOWN
      37 -> PORTDUINO
      38 -> ANDROID_SIM
      39 -> DIY_V1
      40 -> NRF52840_PCA10059
      41 -> DR_DEV
      42 -> M5STACK
      43 -> HELTEC_V3
      44 -> HELTEC_WSL_V3
      45 -> BETAFPV_2400_TX
      46 -> BETAFPV_900_NANO_TX
      47 -> RPI_PICO
      48 -> HELTEC_WIRELESS_TRACKER
      49 -> HELTEC_WIRELESS_PAPER
      50 -> T_DECK
      51 -> T_WATCH_S3
      52 -> PICOMPUTER_S3
      53 -> HELTEC_HT62
      54 -> EBYTE_ESP32_S3
      55 -> ESP32_S3_PICO
      56 -> CHATTER_2
      255 -> PRIVATE_HW
      else -> null
    }
  }
}
