// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.LoRaConfig in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * LoRa radio configuration
 */
public class LoRaConfig(
  /**
   * Use preset (if true, ignore bandwidth/spread_factor/coding_rate)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "usePreset",
    schemaIndex = 0,
  )
  public val use_preset: Boolean = false,
  /**
   * Modem preset
   */
  @field:WireField(
    tag = 2,
    adapter = "com.bitchat.lora.meshtastic.proto.ModemPreset#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "modemPreset",
    schemaIndex = 1,
  )
  public val modem_preset: ModemPreset = ModemPreset.LONG_FAST,
  /**
   * Bandwidth in kHz (125, 250, 500)
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val bandwidth: Int = 0,
  /**
   * Spread factor (7-12)
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "spreadFactor",
    schemaIndex = 3,
  )
  public val spread_factor: Int = 0,
  /**
   * Coding rate (5-8)
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "codingRate",
    schemaIndex = 4,
  )
  public val coding_rate: Int = 0,
  /**
   * Frequency offset in Hz
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "frequencyOffset",
    schemaIndex = 5,
  )
  public val frequency_offset: Float = 0f,
  /**
   * Region
   */
  @field:WireField(
    tag = 7,
    adapter = "com.bitchat.lora.meshtastic.proto.RegionCode#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val region: RegionCode = RegionCode.UNSET_REGION,
  /**
   * Hop limit
   */
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "hopLimit",
    schemaIndex = 7,
  )
  public val hop_limit: Int = 0,
  /**
   * TX enabled
   */
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "txEnabled",
    schemaIndex = 8,
  )
  public val tx_enabled: Boolean = false,
  /**
   * TX power in dBm
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "txPower",
    schemaIndex = 9,
  )
  public val tx_power: Int = 0,
  /**
   * FREQUENCY SLOT (channel_num) - determines the RF frequency
   */
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "channelNum",
    schemaIndex = 10,
  )
  public val channel_num: Int = 0,
  /**
   * Override duty cycle (for testing only)
   */
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "overrideDutyCycle",
    schemaIndex = 11,
  )
  public val override_duty_cycle: Boolean = false,
  /**
   * Ignore incoming messages (for testing)
   */
  @field:WireField(
    tag = 103,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "ignoreIncoming",
    schemaIndex = 12,
  )
  public val ignore_incoming: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LoRaConfig, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LoRaConfig) return false
    if (unknownFields != other.unknownFields) return false
    if (use_preset != other.use_preset) return false
    if (modem_preset != other.modem_preset) return false
    if (bandwidth != other.bandwidth) return false
    if (spread_factor != other.spread_factor) return false
    if (coding_rate != other.coding_rate) return false
    if (frequency_offset != other.frequency_offset) return false
    if (region != other.region) return false
    if (hop_limit != other.hop_limit) return false
    if (tx_enabled != other.tx_enabled) return false
    if (tx_power != other.tx_power) return false
    if (channel_num != other.channel_num) return false
    if (override_duty_cycle != other.override_duty_cycle) return false
    if (ignore_incoming != other.ignore_incoming) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + use_preset.hashCode()
      result = result * 37 + modem_preset.hashCode()
      result = result * 37 + bandwidth.hashCode()
      result = result * 37 + spread_factor.hashCode()
      result = result * 37 + coding_rate.hashCode()
      result = result * 37 + frequency_offset.hashCode()
      result = result * 37 + region.hashCode()
      result = result * 37 + hop_limit.hashCode()
      result = result * 37 + tx_enabled.hashCode()
      result = result * 37 + tx_power.hashCode()
      result = result * 37 + channel_num.hashCode()
      result = result * 37 + override_duty_cycle.hashCode()
      result = result * 37 + ignore_incoming.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """use_preset=$use_preset"""
    result += """modem_preset=$modem_preset"""
    result += """bandwidth=$bandwidth"""
    result += """spread_factor=$spread_factor"""
    result += """coding_rate=$coding_rate"""
    result += """frequency_offset=$frequency_offset"""
    result += """region=$region"""
    result += """hop_limit=$hop_limit"""
    result += """tx_enabled=$tx_enabled"""
    result += """tx_power=$tx_power"""
    result += """channel_num=$channel_num"""
    result += """override_duty_cycle=$override_duty_cycle"""
    result += """ignore_incoming=$ignore_incoming"""
    return result.joinToString(prefix = "LoRaConfig{", separator = ", ", postfix = "}")
  }

  public fun copy(
    use_preset: Boolean = this.use_preset,
    modem_preset: ModemPreset = this.modem_preset,
    bandwidth: Int = this.bandwidth,
    spread_factor: Int = this.spread_factor,
    coding_rate: Int = this.coding_rate,
    frequency_offset: Float = this.frequency_offset,
    region: RegionCode = this.region,
    hop_limit: Int = this.hop_limit,
    tx_enabled: Boolean = this.tx_enabled,
    tx_power: Int = this.tx_power,
    channel_num: Int = this.channel_num,
    override_duty_cycle: Boolean = this.override_duty_cycle,
    ignore_incoming: Boolean = this.ignore_incoming,
    unknownFields: ByteString = this.unknownFields,
  ): LoRaConfig = LoRaConfig(use_preset, modem_preset, bandwidth, spread_factor, coding_rate, frequency_offset, region, hop_limit, tx_enabled, tx_power, channel_num, override_duty_cycle, ignore_incoming, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LoRaConfig> = object : ProtoAdapter<LoRaConfig>(
      FieldEncoding.LENGTH_DELIMITED, 
      LoRaConfig::class, 
      "type.googleapis.com/meshtastic.LoRaConfig", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: LoRaConfig): Int {
        var size = value.unknownFields.size
        if (value.use_preset != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(1, value.use_preset)
        }
        if (value.modem_preset != com.bitchat.lora.meshtastic.proto.ModemPreset.LONG_FAST) {
          size += ModemPreset.ADAPTER.encodedSizeWithTag(2, value.modem_preset)
        }
        if (value.bandwidth != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(3, value.bandwidth)
        }
        if (value.spread_factor != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(4, value.spread_factor)
        }
        if (value.coding_rate != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(5, value.coding_rate)
        }
        if (!value.frequency_offset.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(6, value.frequency_offset)
        }
        if (value.region != com.bitchat.lora.meshtastic.proto.RegionCode.UNSET_REGION) {
          size += RegionCode.ADAPTER.encodedSizeWithTag(7, value.region)
        }
        if (value.hop_limit != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(8, value.hop_limit)
        }
        if (value.tx_enabled != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(9, value.tx_enabled)
        }
        if (value.tx_power != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(10, value.tx_power)
        }
        if (value.channel_num != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(11, value.channel_num)
        }
        if (value.override_duty_cycle != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(12, value.override_duty_cycle)
        }
        if (value.ignore_incoming != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(103, value.ignore_incoming)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LoRaConfig) {
        if (value.use_preset != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.use_preset)
        }
        if (value.modem_preset != com.bitchat.lora.meshtastic.proto.ModemPreset.LONG_FAST) {
          ModemPreset.ADAPTER.encodeWithTag(writer, 2, value.modem_preset)
        }
        if (value.bandwidth != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.bandwidth)
        }
        if (value.spread_factor != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 4, value.spread_factor)
        }
        if (value.coding_rate != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 5, value.coding_rate)
        }
        if (!value.frequency_offset.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 6, value.frequency_offset)
        }
        if (value.region != com.bitchat.lora.meshtastic.proto.RegionCode.UNSET_REGION) {
          RegionCode.ADAPTER.encodeWithTag(writer, 7, value.region)
        }
        if (value.hop_limit != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 8, value.hop_limit)
        }
        if (value.tx_enabled != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 9, value.tx_enabled)
        }
        if (value.tx_power != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 10, value.tx_power)
        }
        if (value.channel_num != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 11, value.channel_num)
        }
        if (value.override_duty_cycle != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 12, value.override_duty_cycle)
        }
        if (value.ignore_incoming != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 103, value.ignore_incoming)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LoRaConfig) {
        writer.writeBytes(value.unknownFields)
        if (value.ignore_incoming != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 103, value.ignore_incoming)
        }
        if (value.override_duty_cycle != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 12, value.override_duty_cycle)
        }
        if (value.channel_num != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 11, value.channel_num)
        }
        if (value.tx_power != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 10, value.tx_power)
        }
        if (value.tx_enabled != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 9, value.tx_enabled)
        }
        if (value.hop_limit != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 8, value.hop_limit)
        }
        if (value.region != com.bitchat.lora.meshtastic.proto.RegionCode.UNSET_REGION) {
          RegionCode.ADAPTER.encodeWithTag(writer, 7, value.region)
        }
        if (!value.frequency_offset.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 6, value.frequency_offset)
        }
        if (value.coding_rate != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 5, value.coding_rate)
        }
        if (value.spread_factor != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 4, value.spread_factor)
        }
        if (value.bandwidth != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.bandwidth)
        }
        if (value.modem_preset != com.bitchat.lora.meshtastic.proto.ModemPreset.LONG_FAST) {
          ModemPreset.ADAPTER.encodeWithTag(writer, 2, value.modem_preset)
        }
        if (value.use_preset != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.use_preset)
        }
      }

      override fun decode(reader: ProtoReader): LoRaConfig {
        var use_preset: Boolean = false
        var modem_preset: ModemPreset = ModemPreset.LONG_FAST
        var bandwidth: Int = 0
        var spread_factor: Int = 0
        var coding_rate: Int = 0
        var frequency_offset: Float = 0f
        var region: RegionCode = RegionCode.UNSET_REGION
        var hop_limit: Int = 0
        var tx_enabled: Boolean = false
        var tx_power: Int = 0
        var channel_num: Int = 0
        var override_duty_cycle: Boolean = false
        var ignore_incoming: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> use_preset = ProtoAdapter.BOOL.decode(reader)
            2 -> try {
              modem_preset = ModemPreset.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            3 -> bandwidth = ProtoAdapter.UINT32.decode(reader)
            4 -> spread_factor = ProtoAdapter.UINT32.decode(reader)
            5 -> coding_rate = ProtoAdapter.UINT32.decode(reader)
            6 -> frequency_offset = ProtoAdapter.FLOAT.decode(reader)
            7 -> try {
              region = RegionCode.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            8 -> hop_limit = ProtoAdapter.UINT32.decode(reader)
            9 -> tx_enabled = ProtoAdapter.BOOL.decode(reader)
            10 -> tx_power = ProtoAdapter.INT32.decode(reader)
            11 -> channel_num = ProtoAdapter.UINT32.decode(reader)
            12 -> override_duty_cycle = ProtoAdapter.BOOL.decode(reader)
            103 -> ignore_incoming = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return LoRaConfig(
          use_preset = use_preset,
          modem_preset = modem_preset,
          bandwidth = bandwidth,
          spread_factor = spread_factor,
          coding_rate = coding_rate,
          frequency_offset = frequency_offset,
          region = region,
          hop_limit = hop_limit,
          tx_enabled = tx_enabled,
          tx_power = tx_power,
          channel_num = channel_num,
          override_duty_cycle = override_duty_cycle,
          ignore_incoming = ignore_incoming,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LoRaConfig): LoRaConfig = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
