// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.MeshPacket in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * A mesh packet
 */
public class MeshPacket(
  /**
   * Sending node number
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val from: Int = 0,
  /**
   * Destination node number (0xFFFFFFFF = broadcast)
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val to: Int = 0,
  /**
   * Channel index
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val channel: Int = 0,
  /**
   * Decoded data
   */
  @field:WireField(
    tag = 4,
    adapter = "com.bitchat.lora.meshtastic.proto.Data#ADAPTER",
    oneofName = "payload_variant",
    schemaIndex = 3,
  )
  public val decoded: Data? = null,
  /**
   * Encrypted payload
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    oneofName = "payload_variant",
    schemaIndex = 4,
  )
  public val encrypted: ByteString? = null,
  /**
   * Unique packet ID
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val id: Int = 0,
  /**
   * Time packet was received (seconds since boot)
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "rxTime",
    schemaIndex = 6,
  )
  public val rx_time: Int = 0,
  /**
   * SNR of received packet
   */
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "rxSnr",
    schemaIndex = 7,
  )
  public val rx_snr: Float = 0f,
  /**
   * Hop limit
   */
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "hopLimit",
    schemaIndex = 8,
  )
  public val hop_limit: Int = 0,
  /**
   * Want acknowledgment?
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "wantAck",
    schemaIndex = 9,
  )
  public val want_ack: Boolean = false,
  /**
   * Priority
   */
  @field:WireField(
    tag = 11,
    adapter = "com.bitchat.lora.meshtastic.proto.Priority#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val priority: Priority = Priority.UNSET_PRIORITY,
  /**
   * RSSI of received packet
   */
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "rxRssi",
    schemaIndex = 11,
  )
  public val rx_rssi: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MeshPacket, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(decoded, encrypted) <= 1) {
      "At most one of decoded, encrypted may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MeshPacket) return false
    if (unknownFields != other.unknownFields) return false
    if (from != other.from) return false
    if (to != other.to) return false
    if (channel != other.channel) return false
    if (decoded != other.decoded) return false
    if (encrypted != other.encrypted) return false
    if (id != other.id) return false
    if (rx_time != other.rx_time) return false
    if (rx_snr != other.rx_snr) return false
    if (hop_limit != other.hop_limit) return false
    if (want_ack != other.want_ack) return false
    if (priority != other.priority) return false
    if (rx_rssi != other.rx_rssi) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + from.hashCode()
      result = result * 37 + to.hashCode()
      result = result * 37 + channel.hashCode()
      result = result * 37 + (decoded?.hashCode() ?: 0)
      result = result * 37 + (encrypted?.hashCode() ?: 0)
      result = result * 37 + id.hashCode()
      result = result * 37 + rx_time.hashCode()
      result = result * 37 + rx_snr.hashCode()
      result = result * 37 + hop_limit.hashCode()
      result = result * 37 + want_ack.hashCode()
      result = result * 37 + priority.hashCode()
      result = result * 37 + rx_rssi.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """from=$from"""
    result += """to=$to"""
    result += """channel=$channel"""
    if (decoded != null) result += """decoded=$decoded"""
    if (encrypted != null) result += """encrypted=$encrypted"""
    result += """id=$id"""
    result += """rx_time=$rx_time"""
    result += """rx_snr=$rx_snr"""
    result += """hop_limit=$hop_limit"""
    result += """want_ack=$want_ack"""
    result += """priority=$priority"""
    result += """rx_rssi=$rx_rssi"""
    return result.joinToString(prefix = "MeshPacket{", separator = ", ", postfix = "}")
  }

  public fun copy(
    from: Int = this.from,
    to: Int = this.to,
    channel: Int = this.channel,
    decoded: Data? = this.decoded,
    encrypted: ByteString? = this.encrypted,
    id: Int = this.id,
    rx_time: Int = this.rx_time,
    rx_snr: Float = this.rx_snr,
    hop_limit: Int = this.hop_limit,
    want_ack: Boolean = this.want_ack,
    priority: Priority = this.priority,
    rx_rssi: Int = this.rx_rssi,
    unknownFields: ByteString = this.unknownFields,
  ): MeshPacket = MeshPacket(from, to, channel, decoded, encrypted, id, rx_time, rx_snr, hop_limit, want_ack, priority, rx_rssi, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MeshPacket> = object : ProtoAdapter<MeshPacket>(
      FieldEncoding.LENGTH_DELIMITED, 
      MeshPacket::class, 
      "type.googleapis.com/meshtastic.MeshPacket", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: MeshPacket): Int {
        var size = value.unknownFields.size
        if (value.from != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(1, value.from)
        }
        if (value.to != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(2, value.to)
        }
        if (value.channel != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(3, value.channel)
        }
        size += Data.ADAPTER.encodedSizeWithTag(4, value.decoded)
        size += ProtoAdapter.BYTES.encodedSizeWithTag(5, value.encrypted)
        if (value.id != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(6, value.id)
        }
        if (value.rx_time != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(7, value.rx_time)
        }
        if (!value.rx_snr.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(8, value.rx_snr)
        }
        if (value.hop_limit != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(9, value.hop_limit)
        }
        if (value.want_ack != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(10, value.want_ack)
        }
        if (value.priority != com.bitchat.lora.meshtastic.proto.Priority.UNSET_PRIORITY) {
          size += Priority.ADAPTER.encodedSizeWithTag(11, value.priority)
        }
        if (value.rx_rssi != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(12, value.rx_rssi)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: MeshPacket) {
        if (value.from != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 1, value.from)
        }
        if (value.to != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 2, value.to)
        }
        if (value.channel != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.channel)
        }
        if (value.id != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 6, value.id)
        }
        if (value.rx_time != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 7, value.rx_time)
        }
        if (!value.rx_snr.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 8, value.rx_snr)
        }
        if (value.hop_limit != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 9, value.hop_limit)
        }
        if (value.want_ack != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 10, value.want_ack)
        }
        if (value.priority != com.bitchat.lora.meshtastic.proto.Priority.UNSET_PRIORITY) {
          Priority.ADAPTER.encodeWithTag(writer, 11, value.priority)
        }
        if (value.rx_rssi != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 12, value.rx_rssi)
        }
        Data.ADAPTER.encodeWithTag(writer, 4, value.decoded)
        ProtoAdapter.BYTES.encodeWithTag(writer, 5, value.encrypted)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MeshPacket) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.BYTES.encodeWithTag(writer, 5, value.encrypted)
        Data.ADAPTER.encodeWithTag(writer, 4, value.decoded)
        if (value.rx_rssi != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 12, value.rx_rssi)
        }
        if (value.priority != com.bitchat.lora.meshtastic.proto.Priority.UNSET_PRIORITY) {
          Priority.ADAPTER.encodeWithTag(writer, 11, value.priority)
        }
        if (value.want_ack != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 10, value.want_ack)
        }
        if (value.hop_limit != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 9, value.hop_limit)
        }
        if (!value.rx_snr.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 8, value.rx_snr)
        }
        if (value.rx_time != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 7, value.rx_time)
        }
        if (value.id != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 6, value.id)
        }
        if (value.channel != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.channel)
        }
        if (value.to != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 2, value.to)
        }
        if (value.from != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 1, value.from)
        }
      }

      override fun decode(reader: ProtoReader): MeshPacket {
        var from: Int = 0
        var to: Int = 0
        var channel: Int = 0
        var decoded: Data? = null
        var encrypted: ByteString? = null
        var id: Int = 0
        var rx_time: Int = 0
        var rx_snr: Float = 0f
        var hop_limit: Int = 0
        var want_ack: Boolean = false
        var priority: Priority = Priority.UNSET_PRIORITY
        var rx_rssi: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> from = ProtoAdapter.FIXED32.decode(reader)
            2 -> to = ProtoAdapter.FIXED32.decode(reader)
            3 -> channel = ProtoAdapter.UINT32.decode(reader)
            4 -> decoded = Data.ADAPTER.decode(reader)
            5 -> encrypted = ProtoAdapter.BYTES.decode(reader)
            6 -> id = ProtoAdapter.FIXED32.decode(reader)
            7 -> rx_time = ProtoAdapter.FIXED32.decode(reader)
            8 -> rx_snr = ProtoAdapter.FLOAT.decode(reader)
            9 -> hop_limit = ProtoAdapter.UINT32.decode(reader)
            10 -> want_ack = ProtoAdapter.BOOL.decode(reader)
            11 -> try {
              priority = Priority.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            12 -> rx_rssi = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MeshPacket(
          from = from,
          to = to,
          channel = channel,
          decoded = decoded,
          encrypted = encrypted,
          id = id,
          rx_time = rx_time,
          rx_snr = rx_snr,
          hop_limit = hop_limit,
          want_ack = want_ack,
          priority = priority,
          rx_rssi = rx_rssi,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MeshPacket): MeshPacket = value.copy(
        decoded = value.decoded?.let(Data.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
