// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.ModemPreset in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * LoRa modem presets
 */
public enum class ModemPreset(
  override val `value`: Int,
) : WireEnum {
  LONG_FAST(0),
  LONG_SLOW(1),
  VERY_LONG_SLOW(2),
  MEDIUM_SLOW(3),
  MEDIUM_FAST(4),
  SHORT_SLOW(5),
  SHORT_FAST(6),
  LONG_MODERATE(7),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ModemPreset> = object : EnumAdapter<ModemPreset>(
      ModemPreset::class, 
      PROTO_3, 
      ModemPreset.LONG_FAST
    ) {
      override fun fromValue(`value`: Int): ModemPreset? = ModemPreset.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): ModemPreset? = when (`value`) {
      0 -> LONG_FAST
      1 -> LONG_SLOW
      2 -> VERY_LONG_SLOW
      3 -> MEDIUM_SLOW
      4 -> MEDIUM_FAST
      5 -> SHORT_SLOW
      6 -> SHORT_FAST
      7 -> LONG_MODERATE
      else -> null
    }
  }
}
