// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.MyNodeInfo in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * My node info (local device)
 */
public class MyNodeInfo(
  /**
   * My node number
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "myNodeNum",
    schemaIndex = 0,
  )
  public val my_node_num: Int = 0,
  /**
   * Firmware version
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "firmwareVersion",
    schemaIndex = 1,
  )
  public val firmware_version: String = "",
  /**
   * Reboot count
   */
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "rebootCount",
    schemaIndex = 2,
  )
  public val reboot_count: Int = 0,
  /**
   * Min app version supported
   */
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "minAppVersion",
    schemaIndex = 3,
  )
  public val min_app_version: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<MyNodeInfo, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is MyNodeInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (my_node_num != other.my_node_num) return false
    if (firmware_version != other.firmware_version) return false
    if (reboot_count != other.reboot_count) return false
    if (min_app_version != other.min_app_version) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + my_node_num.hashCode()
      result = result * 37 + firmware_version.hashCode()
      result = result * 37 + reboot_count.hashCode()
      result = result * 37 + min_app_version.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """my_node_num=$my_node_num"""
    result += """firmware_version=${sanitize(firmware_version)}"""
    result += """reboot_count=$reboot_count"""
    result += """min_app_version=$min_app_version"""
    return result.joinToString(prefix = "MyNodeInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    my_node_num: Int = this.my_node_num,
    firmware_version: String = this.firmware_version,
    reboot_count: Int = this.reboot_count,
    min_app_version: Int = this.min_app_version,
    unknownFields: ByteString = this.unknownFields,
  ): MyNodeInfo = MyNodeInfo(my_node_num, firmware_version, reboot_count, min_app_version, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<MyNodeInfo> = object : ProtoAdapter<MyNodeInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      MyNodeInfo::class, 
      "type.googleapis.com/meshtastic.MyNodeInfo", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: MyNodeInfo): Int {
        var size = value.unknownFields.size
        if (value.my_node_num != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.my_node_num)
        }
        if (value.firmware_version != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.firmware_version)
        }
        if (value.reboot_count != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(8, value.reboot_count)
        }
        if (value.min_app_version != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(11, value.min_app_version)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: MyNodeInfo) {
        if (value.my_node_num != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.my_node_num)
        }
        if (value.firmware_version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.firmware_version)
        }
        if (value.reboot_count != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 8, value.reboot_count)
        }
        if (value.min_app_version != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 11, value.min_app_version)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: MyNodeInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.min_app_version != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 11, value.min_app_version)
        }
        if (value.reboot_count != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 8, value.reboot_count)
        }
        if (value.firmware_version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.firmware_version)
        }
        if (value.my_node_num != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.my_node_num)
        }
      }

      override fun decode(reader: ProtoReader): MyNodeInfo {
        var my_node_num: Int = 0
        var firmware_version: String = ""
        var reboot_count: Int = 0
        var min_app_version: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> my_node_num = ProtoAdapter.UINT32.decode(reader)
            6 -> firmware_version = ProtoAdapter.STRING.decode(reader)
            8 -> reboot_count = ProtoAdapter.UINT32.decode(reader)
            11 -> min_app_version = ProtoAdapter.UINT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return MyNodeInfo(
          my_node_num = my_node_num,
          firmware_version = firmware_version,
          reboot_count = reboot_count,
          min_app_version = min_app_version,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: MyNodeInfo): MyNodeInfo = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
