// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.NodeInfo in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Information about a node on the mesh
 */
public class NodeInfo(
  /**
   * Node number (unique ID on mesh)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val num: Int = 0,
  /**
   * User info
   */
  @field:WireField(
    tag = 2,
    adapter = "com.bitchat.lora.meshtastic.proto.User#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val user: User? = null,
  /**
   * Position info
   */
  @field:WireField(
    tag = 3,
    adapter = "com.bitchat.lora.meshtastic.proto.Position#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val position: Position? = null,
  /**
   * SNR of last received packet
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val snr: Float = 0f,
  /**
   * Last time we heard from this node (seconds since 1970)
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lastHeard",
    schemaIndex = 4,
  )
  public val last_heard: Int = 0,
  /**
   * Device metrics
   */
  @field:WireField(
    tag = 6,
    adapter = "com.bitchat.lora.meshtastic.proto.DeviceMetrics#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "deviceMetrics",
    schemaIndex = 5,
  )
  public val device_metrics: DeviceMetrics? = null,
  /**
   * Hops away (0 = direct)
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "hopsAway",
    schemaIndex = 6,
  )
  public val hops_away: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<NodeInfo, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is NodeInfo) return false
    if (unknownFields != other.unknownFields) return false
    if (num != other.num) return false
    if (user != other.user) return false
    if (position != other.position) return false
    if (snr != other.snr) return false
    if (last_heard != other.last_heard) return false
    if (device_metrics != other.device_metrics) return false
    if (hops_away != other.hops_away) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + num.hashCode()
      result = result * 37 + (user?.hashCode() ?: 0)
      result = result * 37 + (position?.hashCode() ?: 0)
      result = result * 37 + snr.hashCode()
      result = result * 37 + last_heard.hashCode()
      result = result * 37 + (device_metrics?.hashCode() ?: 0)
      result = result * 37 + hops_away.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """num=$num"""
    if (user != null) result += """user=$user"""
    if (position != null) result += """position=$position"""
    result += """snr=$snr"""
    result += """last_heard=$last_heard"""
    if (device_metrics != null) result += """device_metrics=$device_metrics"""
    result += """hops_away=$hops_away"""
    return result.joinToString(prefix = "NodeInfo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    num: Int = this.num,
    user: User? = this.user,
    position: Position? = this.position,
    snr: Float = this.snr,
    last_heard: Int = this.last_heard,
    device_metrics: DeviceMetrics? = this.device_metrics,
    hops_away: Int = this.hops_away,
    unknownFields: ByteString = this.unknownFields,
  ): NodeInfo = NodeInfo(num, user, position, snr, last_heard, device_metrics, hops_away, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<NodeInfo> = object : ProtoAdapter<NodeInfo>(
      FieldEncoding.LENGTH_DELIMITED, 
      NodeInfo::class, 
      "type.googleapis.com/meshtastic.NodeInfo", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: NodeInfo): Int {
        var size = value.unknownFields.size
        if (value.num != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(1, value.num)
        }
        if (value.user != null) {
          size += User.ADAPTER.encodedSizeWithTag(2, value.user)
        }
        if (value.position != null) {
          size += Position.ADAPTER.encodedSizeWithTag(3, value.position)
        }
        if (!value.snr.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(4, value.snr)
        }
        if (value.last_heard != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(5, value.last_heard)
        }
        if (value.device_metrics != null) {
          size += DeviceMetrics.ADAPTER.encodedSizeWithTag(6, value.device_metrics)
        }
        if (value.hops_away != 0) {
          size += ProtoAdapter.UINT32.encodedSizeWithTag(7, value.hops_away)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: NodeInfo) {
        if (value.num != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.num)
        }
        if (value.user != null) {
          User.ADAPTER.encodeWithTag(writer, 2, value.user)
        }
        if (value.position != null) {
          Position.ADAPTER.encodeWithTag(writer, 3, value.position)
        }
        if (!value.snr.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.snr)
        }
        if (value.last_heard != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 5, value.last_heard)
        }
        if (value.device_metrics != null) {
          DeviceMetrics.ADAPTER.encodeWithTag(writer, 6, value.device_metrics)
        }
        if (value.hops_away != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 7, value.hops_away)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: NodeInfo) {
        writer.writeBytes(value.unknownFields)
        if (value.hops_away != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 7, value.hops_away)
        }
        if (value.device_metrics != null) {
          DeviceMetrics.ADAPTER.encodeWithTag(writer, 6, value.device_metrics)
        }
        if (value.last_heard != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 5, value.last_heard)
        }
        if (!value.snr.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 4, value.snr)
        }
        if (value.position != null) {
          Position.ADAPTER.encodeWithTag(writer, 3, value.position)
        }
        if (value.user != null) {
          User.ADAPTER.encodeWithTag(writer, 2, value.user)
        }
        if (value.num != 0) {
          ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.num)
        }
      }

      override fun decode(reader: ProtoReader): NodeInfo {
        var num: Int = 0
        var user: User? = null
        var position: Position? = null
        var snr: Float = 0f
        var last_heard: Int = 0
        var device_metrics: DeviceMetrics? = null
        var hops_away: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> num = ProtoAdapter.UINT32.decode(reader)
            2 -> user = User.ADAPTER.decode(reader)
            3 -> position = Position.ADAPTER.decode(reader)
            4 -> snr = ProtoAdapter.FLOAT.decode(reader)
            5 -> last_heard = ProtoAdapter.FIXED32.decode(reader)
            6 -> device_metrics = DeviceMetrics.ADAPTER.decode(reader)
            7 -> hops_away = ProtoAdapter.UINT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return NodeInfo(
          num = num,
          user = user,
          position = position,
          snr = snr,
          last_heard = last_heard,
          device_metrics = device_metrics,
          hops_away = hops_away,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: NodeInfo): NodeInfo = value.copy(
        user = value.user?.let(User.ADAPTER::redact),
        position = value.position?.let(Position.ADAPTER::redact),
        device_metrics = value.device_metrics?.let(DeviceMetrics.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
