// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.PortNum in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Port numbers for different message types
 */
public enum class PortNum(
  override val `value`: Int,
) : WireEnum {
  UNKNOWN_APP(0),
  TEXT_MESSAGE_APP(1),
  REMOTE_HARDWARE_APP(2),
  POSITION_APP(3),
  NODEINFO_APP(4),
  ROUTING_APP(5),
  ADMIN_APP(6),
  TEXT_MESSAGE_COMPRESSED_APP(7),
  WAYPOINT_APP(8),
  AUDIO_APP(9),
  DETECTION_SENSOR_APP(10),
  REPLY_APP(32),
  IP_TUNNEL_APP(33),
  PAXCOUNTER_APP(34),
  SERIAL_APP(64),
  STORE_FORWARD_APP(65),
  RANGE_TEST_APP(66),
  TELEMETRY_APP(67),
  ZPS_APP(68),
  SIMULATOR_APP(69),
  TRACEROUTE_APP(70),
  NEIGHBORINFO_APP(71),
  ATAK_FORWARDER(257),
  PRIVATE_APP(256),
  ATAK_PLUGIN(72),
  MAX_PORTNUM(511),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PortNum> = object : EnumAdapter<PortNum>(
      PortNum::class, 
      PROTO_3, 
      PortNum.UNKNOWN_APP
    ) {
      override fun fromValue(`value`: Int): PortNum? = PortNum.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): PortNum? = when (`value`) {
      0 -> UNKNOWN_APP
      1 -> TEXT_MESSAGE_APP
      2 -> REMOTE_HARDWARE_APP
      3 -> POSITION_APP
      4 -> NODEINFO_APP
      5 -> ROUTING_APP
      6 -> ADMIN_APP
      7 -> TEXT_MESSAGE_COMPRESSED_APP
      8 -> WAYPOINT_APP
      9 -> AUDIO_APP
      10 -> DETECTION_SENSOR_APP
      32 -> REPLY_APP
      33 -> IP_TUNNEL_APP
      34 -> PAXCOUNTER_APP
      64 -> SERIAL_APP
      65 -> STORE_FORWARD_APP
      66 -> RANGE_TEST_APP
      67 -> TELEMETRY_APP
      68 -> ZPS_APP
      69 -> SIMULATOR_APP
      70 -> TRACEROUTE_APP
      71 -> NEIGHBORINFO_APP
      257 -> ATAK_FORWARDER
      256 -> PRIVATE_APP
      72 -> ATAK_PLUGIN
      511 -> MAX_PORTNUM
      else -> null
    }
  }
}
