// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.Position in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * A position message
 */
public class Position(
  /**
   * Latitude: multiply by 1e-7 to get degrees
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#SFIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "latitudeI",
    schemaIndex = 0,
  )
  public val latitude_i: Int = 0,
  /**
   * Longitude: multiply by 1e-7 to get degrees
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#SFIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "longitudeI",
    schemaIndex = 1,
  )
  public val longitude_i: Int = 0,
  /**
   * Altitude in meters above MSL
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val altitude: Int = 0,
  /**
   * Time the position was taken (seconds since 1970)
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FIXED32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val time: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Position, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Position) return false
    if (unknownFields != other.unknownFields) return false
    if (latitude_i != other.latitude_i) return false
    if (longitude_i != other.longitude_i) return false
    if (altitude != other.altitude) return false
    if (time != other.time) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + latitude_i.hashCode()
      result = result * 37 + longitude_i.hashCode()
      result = result * 37 + altitude.hashCode()
      result = result * 37 + time.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """latitude_i=$latitude_i"""
    result += """longitude_i=$longitude_i"""
    result += """altitude=$altitude"""
    result += """time=$time"""
    return result.joinToString(prefix = "Position{", separator = ", ", postfix = "}")
  }

  public fun copy(
    latitude_i: Int = this.latitude_i,
    longitude_i: Int = this.longitude_i,
    altitude: Int = this.altitude,
    time: Int = this.time,
    unknownFields: ByteString = this.unknownFields,
  ): Position = Position(latitude_i, longitude_i, altitude, time, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Position> = object : ProtoAdapter<Position>(
      FieldEncoding.LENGTH_DELIMITED, 
      Position::class, 
      "type.googleapis.com/meshtastic.Position", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: Position): Int {
        var size = value.unknownFields.size
        if (value.latitude_i != 0) {
          size += ProtoAdapter.SFIXED32.encodedSizeWithTag(1, value.latitude_i)
        }
        if (value.longitude_i != 0) {
          size += ProtoAdapter.SFIXED32.encodedSizeWithTag(2, value.longitude_i)
        }
        if (value.altitude != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.altitude)
        }
        if (value.time != 0) {
          size += ProtoAdapter.FIXED32.encodedSizeWithTag(4, value.time)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Position) {
        if (value.latitude_i != 0) {
          ProtoAdapter.SFIXED32.encodeWithTag(writer, 1, value.latitude_i)
        }
        if (value.longitude_i != 0) {
          ProtoAdapter.SFIXED32.encodeWithTag(writer, 2, value.longitude_i)
        }
        if (value.altitude != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.altitude)
        }
        if (value.time != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 4, value.time)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Position) {
        writer.writeBytes(value.unknownFields)
        if (value.time != 0) {
          ProtoAdapter.FIXED32.encodeWithTag(writer, 4, value.time)
        }
        if (value.altitude != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.altitude)
        }
        if (value.longitude_i != 0) {
          ProtoAdapter.SFIXED32.encodeWithTag(writer, 2, value.longitude_i)
        }
        if (value.latitude_i != 0) {
          ProtoAdapter.SFIXED32.encodeWithTag(writer, 1, value.latitude_i)
        }
      }

      override fun decode(reader: ProtoReader): Position {
        var latitude_i: Int = 0
        var longitude_i: Int = 0
        var altitude: Int = 0
        var time: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> latitude_i = ProtoAdapter.SFIXED32.decode(reader)
            2 -> longitude_i = ProtoAdapter.SFIXED32.decode(reader)
            3 -> altitude = ProtoAdapter.INT32.decode(reader)
            4 -> time = ProtoAdapter.FIXED32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Position(
          latitude_i = latitude_i,
          longitude_i = longitude_i,
          altitude = altitude,
          time = time,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Position): Position = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
