// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.Priority in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Packet priority
 */
public enum class Priority(
  override val `value`: Int,
) : WireEnum {
  UNSET_PRIORITY(0),
  MIN_PRIORITY(1),
  BACKGROUND(10),
  DEFAULT_PRIORITY(64),
  RELIABLE(70),
  ACK_PRIORITY(120),
  MAX_PRIORITY(127),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Priority> = object : EnumAdapter<Priority>(
      Priority::class, 
      PROTO_3, 
      Priority.UNSET_PRIORITY
    ) {
      override fun fromValue(`value`: Int): Priority? = Priority.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): Priority? = when (`value`) {
      0 -> UNSET_PRIORITY
      1 -> MIN_PRIORITY
      10 -> BACKGROUND
      64 -> DEFAULT_PRIORITY
      70 -> RELIABLE
      120 -> ACK_PRIORITY
      127 -> MAX_PRIORITY
      else -> null
    }
  }
}
