// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.RegionCode in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * Region codes for LoRa frequency bands
 */
public enum class RegionCode(
  override val `value`: Int,
) : WireEnum {
  UNSET_REGION(0),
  US(1),
  EU_433(2),
  EU_868(3),
  CN(4),
  JP(5),
  ANZ(6),
  KR(7),
  TW(8),
  RU(9),
  IN(10),
  NZ_865(11),
  TH(12),
  LORA_24(13),
  UA_433(14),
  UA_868(15),
  MY_433(16),
  MY_919(17),
  SG_923(18),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<RegionCode> = object : EnumAdapter<RegionCode>(
      RegionCode::class, 
      PROTO_3, 
      RegionCode.UNSET_REGION
    ) {
      override fun fromValue(`value`: Int): RegionCode? = RegionCode.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): RegionCode? = when (`value`) {
      0 -> UNSET_REGION
      1 -> US
      2 -> EU_433
      3 -> EU_868
      4 -> CN
      5 -> JP
      6 -> ANZ
      7 -> KR
      8 -> TW
      9 -> RU
      10 -> IN
      11 -> NZ_865
      12 -> TH
      13 -> LORA_24
      14 -> UA_433
      15 -> UA_868
      16 -> MY_433
      17 -> MY_919
      18 -> SG_923
      else -> null
    }
  }
}
