// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.ToRadio in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Message from app to radio
 */
public class ToRadio(
  /**
   * Packet to send
   */
  @field:WireField(
    tag = 1,
    adapter = "com.bitchat.lora.meshtastic.proto.MeshPacket#ADAPTER",
    oneofName = "payload_variant",
    schemaIndex = 0,
  )
  public val packet: MeshPacket? = null,
  /**
   * Request config (send node's ID)
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#UINT32",
    jsonName = "wantConfigId",
    oneofName = "payload_variant",
    schemaIndex = 1,
  )
  public val want_config_id: Int? = null,
  /**
   * Disconnect (for BLE)
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    oneofName = "payload_variant",
    schemaIndex = 2,
  )
  public val disconnect: Boolean? = null,
  /**
   * Heartbeat (keep connection alive)
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    oneofName = "payload_variant",
    schemaIndex = 3,
  )
  public val heartbeat: Boolean? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ToRadio, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(packet, want_config_id, disconnect, heartbeat) <= 1) {
      "At most one of packet, want_config_id, disconnect, heartbeat may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ToRadio) return false
    if (unknownFields != other.unknownFields) return false
    if (packet != other.packet) return false
    if (want_config_id != other.want_config_id) return false
    if (disconnect != other.disconnect) return false
    if (heartbeat != other.heartbeat) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (packet?.hashCode() ?: 0)
      result = result * 37 + (want_config_id?.hashCode() ?: 0)
      result = result * 37 + (disconnect?.hashCode() ?: 0)
      result = result * 37 + (heartbeat?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (packet != null) result += """packet=$packet"""
    if (want_config_id != null) result += """want_config_id=$want_config_id"""
    if (disconnect != null) result += """disconnect=$disconnect"""
    if (heartbeat != null) result += """heartbeat=$heartbeat"""
    return result.joinToString(prefix = "ToRadio{", separator = ", ", postfix = "}")
  }

  public fun copy(
    packet: MeshPacket? = this.packet,
    want_config_id: Int? = this.want_config_id,
    disconnect: Boolean? = this.disconnect,
    heartbeat: Boolean? = this.heartbeat,
    unknownFields: ByteString = this.unknownFields,
  ): ToRadio = ToRadio(packet, want_config_id, disconnect, heartbeat, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ToRadio> = object : ProtoAdapter<ToRadio>(
      FieldEncoding.LENGTH_DELIMITED, 
      ToRadio::class, 
      "type.googleapis.com/meshtastic.ToRadio", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: ToRadio): Int {
        var size = value.unknownFields.size
        size += MeshPacket.ADAPTER.encodedSizeWithTag(1, value.packet)
        size += ProtoAdapter.UINT32.encodedSizeWithTag(3, value.want_config_id)
        size += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.disconnect)
        size += ProtoAdapter.BOOL.encodedSizeWithTag(5, value.heartbeat)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ToRadio) {
        MeshPacket.ADAPTER.encodeWithTag(writer, 1, value.packet)
        ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.want_config_id)
        ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.disconnect)
        ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.heartbeat)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ToRadio) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.heartbeat)
        ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.disconnect)
        ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.want_config_id)
        MeshPacket.ADAPTER.encodeWithTag(writer, 1, value.packet)
      }

      override fun decode(reader: ProtoReader): ToRadio {
        var packet: MeshPacket? = null
        var want_config_id: Int? = null
        var disconnect: Boolean? = null
        var heartbeat: Boolean? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> packet = MeshPacket.ADAPTER.decode(reader)
            3 -> want_config_id = ProtoAdapter.UINT32.decode(reader)
            4 -> disconnect = ProtoAdapter.BOOL.decode(reader)
            5 -> heartbeat = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ToRadio(
          packet = packet,
          want_config_id = want_config_id,
          disconnect = disconnect,
          heartbeat = heartbeat,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ToRadio): ToRadio = value.copy(
        packet = value.packet?.let(MeshPacket.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
