// Code generated by Wire protocol buffer compiler, do not edit.
// Source: meshtastic.User in meshtastic/mesh.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.bitchat.lora.meshtastic.proto

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * User identity information
 */
public class User(
  /**
   * Unique ID for the user (8 bytes, displayed as hex)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  /**
   * Long name - full display name
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "longName",
    schemaIndex = 1,
  )
  public val long_name: String = "",
  /**
   * Short name - 4 character max abbreviation
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "shortName",
    schemaIndex = 2,
  )
  public val short_name: String = "",
  /**
   * Hardware model
   */
  @field:WireField(
    tag = 6,
    adapter = "com.bitchat.lora.meshtastic.proto.HardwareModel#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "hwModel",
    schemaIndex = 3,
  )
  public val hw_model: HardwareModel = HardwareModel.UNSET,
  /**
   * Is this node licensed as an amateur radio?
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "isLicensed",
    schemaIndex = 4,
  )
  public val is_licensed: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<User, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is User) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (long_name != other.long_name) return false
    if (short_name != other.short_name) return false
    if (hw_model != other.hw_model) return false
    if (is_licensed != other.is_licensed) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + long_name.hashCode()
      result = result * 37 + short_name.hashCode()
      result = result * 37 + hw_model.hashCode()
      result = result * 37 + is_licensed.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    result += """long_name=${sanitize(long_name)}"""
    result += """short_name=${sanitize(short_name)}"""
    result += """hw_model=$hw_model"""
    result += """is_licensed=$is_licensed"""
    return result.joinToString(prefix = "User{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    long_name: String = this.long_name,
    short_name: String = this.short_name,
    hw_model: HardwareModel = this.hw_model,
    is_licensed: Boolean = this.is_licensed,
    unknownFields: ByteString = this.unknownFields,
  ): User = User(id, long_name, short_name, hw_model, is_licensed, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<User> = object : ProtoAdapter<User>(
      FieldEncoding.LENGTH_DELIMITED, 
      User::class, 
      "type.googleapis.com/meshtastic.User", 
      PROTO_3, 
      null, 
      "meshtastic/mesh.proto"
    ) {
      override fun encodedSize(`value`: User): Int {
        var size = value.unknownFields.size
        if (value.id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        }
        if (value.long_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.long_name)
        }
        if (value.short_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.short_name)
        }
        if (value.hw_model != com.bitchat.lora.meshtastic.proto.HardwareModel.UNSET) {
          size += HardwareModel.ADAPTER.encodedSizeWithTag(6, value.hw_model)
        }
        if (value.is_licensed != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(7, value.is_licensed)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: User) {
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
        if (value.long_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.long_name)
        }
        if (value.short_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.short_name)
        }
        if (value.hw_model != com.bitchat.lora.meshtastic.proto.HardwareModel.UNSET) {
          HardwareModel.ADAPTER.encodeWithTag(writer, 6, value.hw_model)
        }
        if (value.is_licensed != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.is_licensed)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: User) {
        writer.writeBytes(value.unknownFields)
        if (value.is_licensed != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.is_licensed)
        }
        if (value.hw_model != com.bitchat.lora.meshtastic.proto.HardwareModel.UNSET) {
          HardwareModel.ADAPTER.encodeWithTag(writer, 6, value.hw_model)
        }
        if (value.short_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.short_name)
        }
        if (value.long_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.long_name)
        }
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): User {
        var id: String = ""
        var long_name: String = ""
        var short_name: String = ""
        var hw_model: HardwareModel = HardwareModel.UNSET
        var is_licensed: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> long_name = ProtoAdapter.STRING.decode(reader)
            3 -> short_name = ProtoAdapter.STRING.decode(reader)
            6 -> try {
              hw_model = HardwareModel.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            7 -> is_licensed = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return User(
          id = id,
          long_name = long_name,
          short_name = short_name,
          hw_model = hw_model,
          is_licensed = is_licensed,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: User): User = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
