#!/usr/bin/env bash
# Snapshot everything a fork-dependent build relies on, so upgrades can be diffed and rolled back.
# Output: docs/baseline/<date>.md (commit it).
set -euo pipefail
export LC_ALL=C  # deterministic sort/hash order regardless of the caller's locale
cd "$(dirname "$0")/.."
DATE="${1:-$(date +%F)}"
OUT="docs/baseline/${DATE}.md"
mkdir -p docs/baseline
M2="${HOME}/.m2/repository"
# Preserve the hand-maintained gate-results section across regenerations.
GATES="$( [ -f "$OUT" ] && sed -n '/^## Gate results/,$p' "$OUT" || true )"

{
  echo "# Build baseline ${DATE}"
  echo
  echo "Generated by \`scripts/baseline-manifest.sh\` on $(uname -m)."
  echo
  echo "## Repo"
  echo '```'
  echo "HEAD $(git rev-parse --short HEAD) $(git branch --show-current) dirty=$(git status --porcelain --ignore-submodules=dirty | grep -vc '^??' || true)"
  git status --porcelain --ignore-submodules=dirty | grep -v '^??' || true
  git submodule status
  echo '```'
  echo
  echo "## Toolchain"
  echo '```'
  grep distributionUrl gradle/wrapper/gradle-wrapper.properties
  sed -n '/^\[versions\]/,/^\[libraries\]/p' gradle/libs.versions.toml | grep -E '^(kotlin|agp|ksp|coroutines|ktor|koin) = ' || true
  grep -E '^embedded\.' gradle.properties
  echo "JAVA_HOME=${JAVA_HOME:-unset}"
  { "${JAVA_HOME:+$JAVA_HOME/bin/}java" -version 2>&1 | head -2; } || echo "java: not found"
  brew list --versions libsodium secp256k1 2>/dev/null || true
  echo '```'
  echo
  echo "## Forks (../forks)"
  echo '```'
  for d in ../forks/*/ ../forks/jake/*/; do
    [ -d "$d/.git" ] || [ -f "$d/.git" ] || continue
    printf '%-40s %s %s dirty=%s\n' "$d" "$(git -C "$d" rev-parse --short HEAD)" "$(git -C "$d" branch --show-current)" "$(git -C "$d" status --porcelain | grep -vc '^??' || true)"
  done
  echo '```'
  echo
  echo "## Local Maven artifacts (fork snapshots; sources/javadoc and non-Linux Koin variants omitted)"
  echo '```'
  # Each find/grep stage is guarded so a missing directory or an empty result on a fresh
  # machine cannot abort this block under pipefail and leave a truncated document.
  { find "$M2/org/jetbrains/compose" "$M2/org/jetbrains/androidx" "$M2/org/jetbrains/skiko" "$M2/io/insert-koin" \
         -type f \( -name '*.jar' -o -name '*.klib' -o -name '*.module' \) \
         -not -name '*-sources.jar' -not -name '*-javadoc.jar' \
         \( -path '*9999.0.0-SNAPSHOT*' -o -path '*0.9.37.3*' -o -path '*/4.1.2/*' \) 2>/dev/null || true; } \
    | { grep -vE '/koin-[^/]+-(watchos|tvos|js|wasm|mingw|ios)[^/]*/' || true; } \
    | sort | while read -r f; do
        h=$(shasum -a 256 "$f" | cut -c1-16) || h="SHASUM-FAILED"
        printf '%s  %s\n' "$h" "${f#$M2/}"
      done
  echo '```'
  echo
  echo "## Prebuilt native artifacts consumed by the build (gitignored)"
  echo '```'
  # The build files link against: native/<lib>/build/<arch>/lib/*.a (libsodium, secp256k1, noise-c),
  # native/libs/<arch>/lib/*.a and native/libs/desktop/*.dylib (arti), gattlib's build/<arch>/install/lib,
  # the hand-built systemd stub archive native/stubs/libsystemd_stubs.a (linked via gattlib.def),
  # and jniLibs/<abi>/*.so (Android arti). Intermediate outputs (.libs/, src/, cargo target/) and
  # sysroots are deliberately excluded.
  # macOS-only: stat -f
  { find data \( -path '*/native/*/build/*/lib/lib*' -o -path '*/native/*/build/*/install/lib/lib*' \
                 -o -path '*/native/libs/*/lib/lib*' -o -path '*/native/libs/desktop/lib*' \
                 -o -path '*/native/stubs/lib*' -o -path '*/jniLibs/*/lib*' \) \
         -type f \( -name '*.a' -o -name '*.so' -o -name '*.dylib' \) -not -path '*/sysroot/*' 2>/dev/null || true; } \
    | sort | while read -r f; do
        h=$(shasum -a 256 "$f" | cut -c1-16) || h="SHASUM-FAILED"
        s=$(stat -f '%z %Sm' -t '%Y-%m-%d' "$f") || s="STAT-FAILED"
        printf '%s  %s  %s\n' "$h" "$s" "$f"
      done
  echo '```'
  echo
  echo "## Native header sets (hash of header contents per include dir the build reads)"
  echo '```'
  # shasum output is stable across macOS/Linux. Dirs mirror the includeDirs()/cinterop settings in data/*/build.gradle.kts.
  for inc in \
    data/crypto/native/libsodium/build/*/include \
    data/crypto/native/secp256k1/build/{ios-arm64,ios-simulator-fat,linux-arm64}/include \
    data/noise/native/noise-c/include \
    data/remote/transport/bluetooth/native/gattlib/include \
    data/remote/transport/bluetooth/native/include \
    data/remote/tor/native/arti-ios-wrapper \
    data/remote/tor/native/arti-linux-wrapper; do
    [ -d "$inc" ] || continue
    n=$(find "$inc" -name '*.h' -type f -not -path '*/target/*' | wc -l | tr -d ' ')
    [ "$n" -gt 0 ] || continue
    h=$(cd "$inc" && find . -name '*.h' -type f -not -path '*/target/*' | sort | xargs shasum -a 256 | shasum -a 256 | cut -c1-16) || h="SHASUM-FAILED"
    printf '%s  %4s headers  %s\n' "$h" "$n" "$inc"
  done
  echo '```'
} > "$OUT.tmp"
if [ -n "$GATES" ]; then printf '\n%s\n' "$GATES" >> "$OUT.tmp"; fi
mv "$OUT.tmp" "$OUT"
echo "wrote $OUT"
